version: '3.9'

services:
  frontend:
    build: .
    container_name: otog-frontend
    restart: unless-stopped
    env_file:
      - .env.production
      - .env.local
    ports:
      - 3000:3000
    networks:
      - otog-network

networks:
  otog-network:
    name: otog-network
