version: '3.9'

services:
  frontend:
    image: ghcr.io/phakphum-dev/otog-frontend:latest
    container_name: otog-frontend
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - 3000:3000
    networks:
      - otog-network

networks:
  otog-network:
    name: otog-network
