version: '3.9'

services:
  frontend:
    image: ghcr.io/phakphum-dev/otog-frontend:latest
    container_name: otog-frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - otog-network
      - api-gateway

networks:
  otog-network:
    name: otog-network
  api-gateway:
    external: true
